/*
 * Copyright (c) 2014 Ingenic Semiconductor, <lhhuang@ingenic.cn>
 * 
 * @references: borrowed heavily from Android bionic code:
 *  bionic/libc/include/sys/_errdefs.h
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */


#ifndef __ERRDEF
#error "__ERRDEF must be defined before including this file"
#endif
__ERRDEF( 0              ,   0, "Success" )
__ERRDEF( EPERM          ,   1, "Operation not permitted" )
__ERRDEF( ENOENT         ,   2, "No such file or directory" )
__ERRDEF( ESRCH          ,   3, "No such process" )
__ERRDEF( EINTR          ,   4, "Interrupted system call" )
__ERRDEF( EIO            ,   5, "I/O error" )
__ERRDEF( ENXIO          ,   6, "No such device or address" )
__ERRDEF( E2BIG          ,   7, "Argument list too long" )
__ERRDEF( ENOEXEC        ,   8, "Exec format error" )
__ERRDEF( EBADF          ,   9, "Bad file number" )
__ERRDEF( ECHILD         ,  10, "No child processes" )
__ERRDEF( EAGAIN         ,  11, "Try again" )
__ERRDEF( ENOMEM         ,  12, "Out of memory" )
__ERRDEF( EACCES         ,  13, "Permission denied" )
__ERRDEF( EFAULT         ,  14, "Bad address" )
__ERRDEF( ENOTBLK        ,  15, "Block device required" )
__ERRDEF( EBUSY          ,  16, "Device or resource busy" )
__ERRDEF( EEXIST         ,  17, "File exists" )
__ERRDEF( EXDEV          ,  18, "Cross-device link" )
__ERRDEF( ENODEV         ,  19, "No such device" )
__ERRDEF( ENOTDIR        ,  20, "Not a directory" )
__ERRDEF( EISDIR         ,  21, "Is a directory" )
__ERRDEF( EINVAL         ,  22, "Invalid argument" )
__ERRDEF( ENFILE         ,  23, "File table overflow" )
__ERRDEF( EMFILE         ,  24, "Too many open files" )
__ERRDEF( ENOTTY         ,  25, "Not a typewriter" )
__ERRDEF( ETXTBSY        ,  26, "Text file busy" )
__ERRDEF( EFBIG          ,  27, "File too large" )
__ERRDEF( ENOSPC         ,  28, "No space left on device" )
__ERRDEF( ESPIPE         ,  29, "Illegal seek" )
__ERRDEF( EROFS          ,  30, "Read-only file system" )
__ERRDEF( EMLINK         ,  31, "Too many links" )
__ERRDEF( EPIPE          ,  32, "Broken pipe" )
__ERRDEF( EDOM           ,  33, "Math argument out of domain of func" )
__ERRDEF( ERANGE         ,  34, "Math result not representable" )
__ERRDEF( EDEADLK        ,  35, "Resource deadlock would occur" )
__ERRDEF( ENAMETOOLONG   ,  36, "File name too long" )
__ERRDEF( ENOLCK         ,  37, "No record locks available" )
__ERRDEF( ENOSYS         ,  38, "Function not implemented" )
__ERRDEF( ENOTEMPTY      ,  39, "Directory not empty" )
__ERRDEF( ELOOP          ,  40, "Too many symbolic links encountered" )
__ERRDEF( ENOMSG         ,  42, "No message of desired type" )
__ERRDEF( EIDRM          ,  43, "Identifier removed" )
__ERRDEF( ECHRNG         ,  44, "Channel number out of range" )
__ERRDEF( EL2NSYNC       ,  45, "Level 2 not synchronized" )
__ERRDEF( EL3HLT         ,  46, "Level 3 halted" )
__ERRDEF( EL3RST         ,  47, "Level 3 reset" )
__ERRDEF( ELNRNG         ,  48, "Link number out of range" )
__ERRDEF( EUNATCH        ,  49, "Protocol driver not attached" )
__ERRDEF( ENOCSI         ,  50, "No CSI structure available" )
__ERRDEF( EL2HLT         ,  51, "Level 2 halted" )
__ERRDEF( EBADE          ,  52, "Invalid exchange" )
__ERRDEF( EBADR          ,  53, "Invalid request descriptor" )
__ERRDEF( EXFULL         ,  54, "Exchange full" )
__ERRDEF( ENOANO         ,  55, "No anode" )
__ERRDEF( EBADRQC        ,  56, "Invalid request code" )
__ERRDEF( EBADSLT        ,  57, "Invalid slot" )
__ERRDEF( EBFONT         ,  59, "Bad font file format" )
__ERRDEF( ENOSTR         ,  60, "Device not a stream" )
__ERRDEF( ENODATA        ,  61, "No data available" )
__ERRDEF( ETIME          ,  62, "Timer expired" )
__ERRDEF( ENOSR          ,  63, "Out of streams resources" )
__ERRDEF( ENONET         ,  64, "Machine is not on the network" )
__ERRDEF( ENOPKG         ,  65, "Package not installed" )
__ERRDEF( EREMOTE        ,  66, "Object is remote" )
__ERRDEF( ENOLINK        ,  67, "Link has been severed" )
__ERRDEF( EADV           ,  68, "Advertise error" )
__ERRDEF( ESRMNT         ,  69, "Srmount error" )
__ERRDEF( ECOMM          ,  70, "Communication error on send" )
__ERRDEF( EPROTO         ,  71, "Protocol error" )
__ERRDEF( EMULTIHOP      ,  72, "Multihop attempted" )
__ERRDEF( EDOTDOT        ,  73, "RFS specific error" )
__ERRDEF( EBADMSG        ,  74, "Not a data message" )
__ERRDEF( EOVERFLOW      ,  75, "Value too large for defined data type" )
__ERRDEF( ENOTUNIQ       ,  76, "Name not unique on network" )
__ERRDEF( EBADFD         ,  77, "File descriptor in bad state" )
__ERRDEF( EREMCHG        ,  78, "Remote address changed" )
__ERRDEF( ELIBACC        ,  79, "Can not access a needed shared library" )
__ERRDEF( ELIBBAD        ,  80, "Accessing a corrupted shared library" )
__ERRDEF( ELIBSCN        ,  81, ".lib section in a.out corrupted" )
__ERRDEF( ELIBMAX        ,  82, "Attempting to link in too many shared libraries" )
__ERRDEF( ELIBEXEC       ,  83, "Cannot exec a shared library directly" )
__ERRDEF( EILSEQ         ,  84, "Illegal byte sequence" )
__ERRDEF( ERESTART       ,  85, "Interrupted system call should be restarted" )
__ERRDEF( ESTRPIPE       ,  86, "Streams pipe error" )
__ERRDEF( EUSERS         ,  87, "Too many users" )
__ERRDEF( ENOTSOCK       ,  88, "Socket operation on non-socket" )
__ERRDEF( EDESTADDRREQ   ,  89, "Destination address required" )
__ERRDEF( EMSGSIZE       ,  90, "Message too long" )
__ERRDEF( EPROTOTYPE     ,  91, "Protocol wrong type for socket" )
__ERRDEF( ENOPROTOOPT    ,  92, "Protocol not available" )
__ERRDEF( EPROTONOSUPPORT,  93, "Protocol not supported" )
__ERRDEF( ESOCKTNOSUPPORT,  94, "Socket type not supported" )
__ERRDEF( EOPNOTSUPP     ,  95, "Operation not supported on transport endpoint" )
__ERRDEF( EPFNOSUPPORT   ,  96, "Protocol family not supported" )
__ERRDEF( EAFNOSUPPORT   ,  97, "Address family not supported by protocol" )
__ERRDEF( EADDRINUSE     ,  98, "Address already in use" )
__ERRDEF( EADDRNOTAVAIL  ,  99, "Cannot assign requested address" )
__ERRDEF( ENETDOWN       , 100, "Network is down" )
__ERRDEF( ENETUNREACH    , 101, "Network is unreachable" )
__ERRDEF( ENETRESET      , 102, "Network dropped connection because of reset" )
__ERRDEF( ECONNABORTED   , 103, "Software caused connection abort" )
__ERRDEF( ECONNRESET     , 104, "Connection reset by peer" )
__ERRDEF( ENOBUFS        , 105, "No buffer space available" )
__ERRDEF( EISCONN        , 106, "Transport endpoint is already connected" )
__ERRDEF( ENOTCONN       , 107, "Transport endpoint is not connected" )
__ERRDEF( ESHUTDOWN      , 108, "Cannot send after transport endpoint shutdown" )
__ERRDEF( ETOOMANYREFS   , 109, "Too many references: cannot splice" )
__ERRDEF( ETIMEDOUT      , 110, "Connection timed out" )
__ERRDEF( ECONNREFUSED   , 111, "Connection refused" )
__ERRDEF( EHOSTDOWN      , 112, "Host is down" )
__ERRDEF( EHOSTUNREACH   , 113, "No route to host" )
__ERRDEF( EALREADY       , 114, "Operation already in progress" )
__ERRDEF( EINPROGRESS    , 115, "Operation now in progress" )
__ERRDEF( ESTALE         , 116, "Stale NFS file handle" )
__ERRDEF( EUCLEAN        , 117, "Structure needs cleaning" )
__ERRDEF( ENOTNAM        , 118, "Not a XENIX named type file" )
__ERRDEF( ENAVAIL        , 119, "No XENIX semaphores available" )
__ERRDEF( EISNAM         , 120, "Is a named type file" )
__ERRDEF( EREMOTEIO      , 121, "Remote I/O error" )
__ERRDEF( EDQUOT         , 122, "Quota exceeded" )
__ERRDEF( ENOMEDIUM      , 123, "No medium found" )
__ERRDEF( EMEDIUMTYPE    , 124, "Wrong medium type" )

#undef __ERRDEF
